export const USER_LOGIN_SUCCESSFULL="USER_LOGIN_SUCCESSFULL"
export const USER_REGISTER_SUCCESSFULL="USER_REGISTER_SUCCESSFULL"

export const PRODUCT_REQUEST="PRODUCT_REQUEST"
export const PRODUCT_REQUEST_FAILUER="PRODUCT_REQUEST_FAILUER"
export const PRODUCT_REQUEST_SUCCESSFULL="PRODUCT_REQUEST_SUCCESSFULL"

export const SET_NIGHT_MODE="SET_NIGHT_MODE"
export const SET_MODE="SET_MODE"